### ISSUE TITLE
Can I contact you?

### ISSUE THREAD

**Issue by negezor** [prj-exa/exa#1]
Sorry for being off-topic, you can delete this issue later. But could I contact you about transferring the rights to the crate name in crates.io? Your crate was yanked, so I assumed you didn't need it. The crate is created for the same things as the original.

You can contact me personally on telegram or at the email specified in my GitHub profile.

**Comment by negezor** [comment]
@ori-d could you answer please?

**Comment by ori-d** [comment]
Can u tell me the name of the crate? I didn't understand what r u talking about, then I can check it.

**Comment by negezor** [comment]
@ori-d I mean this crate https://crates.io/crates/kodik
